workflows:
  upload-ipa:
    name: Upload IPA to App Store Connect
    max_build_duration: 120
    instance_type: mac_mini_m2
    working_directory: ios/

    integrations:
      app_store_connect: CodeMagic Integration Key

    environment:
      vars:
        APP_STORE_APPLE_ID: 6745644715 # Your App Store Connect App ID

    artifacts:
      - build/ipa/MellyBabyShop.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

      email:
        recipients:
          - andargedaniel90@gmail.com
        notify:
          success: true
          failure: true
