workflows:
  ios-workflow:
    name: Melly Baby Shop iOS Build
    working_directory: ios/
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: co.mellybabyshop.co.za
        team_id: UVKRVXQ95Z # Your Apple Team ID
        certificate_type: apple_distribution

      vars:
        BUNDLE_ID: 'co.mellybabyshop.co.za'
        XCODE_WORKSPACE: 'MellyBabyShop.xcworkspace'
        XCODE_SCHEME: 'MellyBabyShop'
        APP_STORE_APPLE_ID: 6745569837

      xcode: latest

    scripts:
      - name: Verify Bundle Identifier
        script: |
          # Ensure bundle ID matches provisioning profile
          plutil -replace CFBundleIdentifier -string "$BUNDLE_ID" LeanIOS/Info.plist
          plutil -replace CFBundleIdentifier -string "$BUNDLE_ID" LeanIOSTests/Info.plist

      - name: Set up provisioning profiles
        script: |
          xcode-project use-profiles \
            --team-id UVKRVXQ95Z \
            --bundle-identifier "$BUNDLE_ID"

      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build IPA with Destination
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - andargedaniel90@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
